### ISSUE TITLE
Tracking Issue - MSRV bump (post 1.41.1)

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1060]
At some stage (in a few years) we will want to bump the MSRV again, this is a tracking issue for possible changes at such a time

- [x] Use `matches!` macro - came in in Rust 1.42 
- [x] Use `#[track_caller]` [in `secp256k1`](https://github.com/rust-bitcoin/rust-secp256k1/pull/458#discussion_r903334612) and maybe elsewhere; Rust 1.46 
- [x] slice patterns instead of `copy_from_slice` where relevant; Rust 1.42
- [x] Remove `unsigned_abs` from `src/util/amount` and use [`i8::unsigned_abs()`](https://doc.rust-lang.org/core/primitive.i8.html#method.unsigned_abs); Rust 1.51

**Comment by apoelstra** [comment]
I'm not sure we have an application but in https://github.com/apoelstra/rust-jsonrpc/pull/70 we wanted to do something like `let (self.a, self.b) = function_returning_a_tuple()` which is a pretty great idiom that's easier to read and can often eliminate the need for temporary variables. (Like, you can write `(a, b) = (b, a)`.)

**Comment by jkczyz** [comment]
Would be nice to make `ChainHash::using_genesis_block` a `const` function. Needs 1.46 for added `match` support: https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html#const-fn-improvements.

An interim solution may be to expose individual constants.

**Comment by tcharding** [comment]
Or we could provide 4 functions of form:
```rust

    /// Returns the hash of the mainnet (Bitcoin) genesis block for use as a chain hash.
    pub const fn using_mainnet_genesis_block() -> Self {
        ChainHash(GENESIS_BLOCK_HASH_BITCOIN)
    }
```

**Comment by jkczyz** [comment]
Drafted the constant approach in https://github.com/rust-bitcoin/rust-bitcoin/pull/1283 for consideration.

**Comment by tcharding** [comment]
Ha! Your PR was way better than my suggestion :)

**Comment by jkczyz** [comment]
Note, should revert #1286 once MSRV is 1.46 or greater.

**Comment by apoelstra** [comment]
I don't know if it's relevant to us, but TIL that 1.63 (released this august) has `Mutex::new` as a constexpr!! https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html

**Comment by apoelstra** [comment]
1.45 has `char` ranges https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html which is a super minor thing but may be useful for our various string encodings (base32/58/64) to avoid hardcoded `"abcdefghijklmnopqrstuvwxyz"` type strings.

**Comment by Kixunil** [comment]
I don't remember seeing any mutexes or threaded code in any of the libraries but it sure is nice if we ever have it. Char ranges are cool but `clippy` says that `(a..b).contains('B')` is more readable than `a <= 'B' && 'B' < b` which I disagree with (but `'B'.in_range(a..b)` would be better).

**Comment by Kixunil** [comment]
I would be highly surprised if it was impossible in 1.48. From what I've seen all operations SHA256 uses are implementable with operator which IIRC were available as cont fn from the beginning. So the only thing that was missing were loops which were made const in 1.46

**Comment by Kixunil** [comment]
We did everything suggested here, so I'm closing this, we can open another one for next MSRV bump.

**Comment by Kixunil** [comment]
Openendd #2411
