### ISSUE TITLE
Tracking PSBT refactoring & PSBTv2 Epic

### ISSUE THREAD

**Issue by DanGould** [rust-bitcoin/rust-bitcoin#1115]
This is a tracking issue for ongoing PSBT work, including but not limited to implementing support for PSBT v2 [BIP-370](https://github.com/bitcoin/bips/blob/master/bip-0370.mediawiki).

For reference we do support PSBT v0 [BIP-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki).

We can look to the achow101 PR https://github.com/bitcoin/bitcoin/pull/21283 for guidance since he's the BIP-370 author.

# 1️⃣ Refactor 

## Refactor PSBT Consensus Encoding Traits

Now we implement consensus::Encodable and Decodable for PSBT types. We should not implement those traits since PSBT data moves at the application layer and not at the p2p consensus layer. We may consider removing serde support for PSBT or reimplement it using BIP-174 serialization spec base64 or binary. We should remove the Consensus Encoding traits as we roll out PSBTv2, or else we're building deeper into a regressive pattern.

- [x] Serialize without Consensus Traits 
  - [x] https://github.com/rust-bitcoin/rust-bitcoin/issues/934
  - [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/988 

## Improve Psbt Error handling

- [x] https://github.com/rust-bitcoin/rust-bitcoin/issues/837 circular dependencies, Parse(String), dependence on consensus Error types
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/1310
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/1532
- [x] #1589
- [x] https://github.com/rust-bitcoin/rust-bitcoin/issues/1590 https://github.com/rust-bitcoin/rust-bitcoin/pull/1609

# 2️⃣ Add PSBTv2

PSBTv2 allows inputs and outputs to be added to (and removed from) the PSBT after creation. To do this the struct eliminates the global unsigned transaction. Input and output maps replace it. Each element of those maps has complete information about each input or output. **Shipping PSBTv2 is the primary goal  of this epic**

[**Discussion**](https://github.com/rust-bitcoin/rust-bitcoin/discussions/1921)

- [ ] https://github.com/rust-bitcoin/rust-bitcoin/pull/1924
- [ ] https://github.com/rust-bitcoin/rust-bitcoin/pull/1218
- [ ] Add new input map
- [ ] Add new output map
- [ ] Add test vectors from BIP-370

## Prior attempts: 

- https://github.com/rust-bitcoin/rust-bitcoin/pull/726
- https://github.com/rust-bitcoin/rust-bitcoin/pull/769

# Document and Exemplify

- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/935
- [x] https://github.com/rust-bitcoin/rust-bitcoin/issues/893 https://github.com/rust-bitcoin/rust-bitcoin/pull/999 good first issue
- [ ] Decide to include a finalizer or include `rust-miniscript` as a dev-dependency for examples https://github.com/rust-bitcoin/rust-bitcoin/issues/630#issuecomment-1189611845

### working standalone psbt crate including v2

The [BP-WG/descriptor-wallet](https://github.com/BP-WG/descriptor-wallet/tree/master/psbt) version supports the internal v2 struct but only v0 de/serialization. That makes working with the psbt a lot easier in rust code with one conversion. It's a neat approach.

# Improve capabilities

## Enable Signing

- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/957

**Comment by tcharding** [comment]
Shall we close this @DanGould and focus on https://github.com/tcharding/rust-psbt?

**Comment by DanGould** [comment]
yes
