### ISSUE TITLE
Epic: Re-write the `hashes` API

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2881]
Re-write the `hashes` API with the following goals:

* [ ] An API where only "general hashes" (i.e. hashes defined by their algorithms) can hash arbitrary data, while "normal hashes" (e.g. `Txid`) can only be constructed from actual transaction data, from deserialization, and from "hash casting" by converting to/from byte arrays.
* [ ] An API where it is easy/obvious how to just hash some data from a file or something.
* [ ] An API where you can define strongly-typed but generic algorithms from general hashes (specifically: Merkle trees, HMAC and PBKDF). To prove this out we should have HMAC defined within the `hashes` lib and at least one Merkle tree impl outside of it (e.g. the one in `bitcoin`).
* [ ] An API which supports BIP-340 tagged hashes in a strongly-typed way.
* [ ] An API where you can at least construct fixed hashes in constfns ... ideally you could actually hash data but ok that's hard.
* [ ] (Eventually) a way to distinguish `KnownPreimage`/`UnknownPreimage` so that we can prevent people from e.g. signing opaque hash blobs without making a solemn oath that they mean to do so. But we should revisit that later because it's a big invasive API change and will likely have its own issues with the Rust language.

The issues we have with this right now are:

* An overuse of the word `Hash` for both traits and hashes; and to do anything, users to name types like `sha256::Hash` which are not discoverable from documentation.
* An overuse of traits for things that don't/rarely need to be generic, which again hurts discoverabliity because users *further* need to import `crate::Hash`.
* An overuse of macros which hides all of the above even from a user who attempts to read the source code.
* Poorly-defined traits which don't distinguish the different uses of hashes and put inappropriate methods onto stuff (e.g. `LegacySighash::all_zeros` which is trivial to forge messages for).

Where we can definitely unambiguously start are:

* Reducing/splitting the existing traits to reduce API surface.
* Adding inherents and constfns.

Where we are hitting difficulty is trying to do stuff generically over general hashes which might have arbitrary digest sizes. I think this will be much more tractable if we do the "easy" stuff first.

Consider also: #3050

**Comment by tcharding** [comment]
Initial exploratory work was done in #2770.

**Comment by Kixunil** [comment]
I'd like the idea of requiring `Digest: IsArray` to be reconsidered. Previously @apoelstra argued that it prevents people from using `ArrayVec` or other niche types. That is true but I've now realized that requiring it to be array has one interesting advantage: we can add more trait bounds later. That means not only we can add more traits that we may forgot but also whenever `std`/`core` adds a new trait (`IntoLendingIterator` maybe?) we can require it which makes usage more convenient. Further, one day we'll be able to say `Digest = [u8; Self::LEN]` once it's stabilized without breaking anything and it'll make usage even easier.

I think this is more realistic/useful than a hypothetical user wanting a different type.

**Comment by apoelstra** [comment]
Yeah, that's a good point. Agreed.

If it were possible to directly constrain it to be `[u8; N]` we would be doing that. So it's not like I'm married to the extra benefit of more generality.... and if it constrains us, I guess it's not worth it.

**Comment by tcharding** [comment]
(Context for readers, I posted this epic but @apoelstra  originally wrote the text.)

Re the six bullet points (now checkboxes), @apoelstra can you please check that you agree with the following reasoning and tick the boxes for which you do?

* An API where only "general hashes" (i.e. hashes defined by their algorithms) can hash arbitrary data, while "normal hashes" (e.g. `Txid`) can only be constructed from actual transaction data, from deserialization, and from "hash casting" by converting to/from byte arrays.

This is completed by #2981 I believe.

* An API where it is easy/obvious how to just hash some data from a file or something.

Is this covered by the crate level examples in `hashes` or did you expect more work for this one?

* An API where you can define strongly-typed but generic algorithms from general hashes (specifically: Merkle trees, HMAC and PBKDF). To prove this out we should have HMAC defined within the `hashes` lib and at least one Merkle tree impl outside of it (e.g. the one in `bitcoin`).

This is done I believe, we have `hmac` and we have the `merkle_tree::MerkleNode` stuff.

* An API which supports BIP-340 tagged hashes in a strongly-typed way.

Not 100% sure what you mean by this one, is `sha256t::Hash` strongly type enough or did you expect more work done there?

* An API where you can at least construct fixed hashes in constfns ... ideally you could actually hash data but ok that's hard.

I believe this is done, we have 

```bash
gg 'pub const fn'
internal_macros.rs:213:            pub const fn to_byte_array(self) -> [u8; $bits / 8] { self.0 }
internal_macros.rs:216:            pub const fn as_byte_array(&self) -> &[u8; $bits / 8] { &self.0 }
internal_macros.rs:219:            pub const fn from_byte_array(bytes: [u8; $bits / 8]) -> Self {
sha256.rs:110:    pub const fn const_hash(bytes: &[u8]) -> Self { Hash(Midstate::const_hash(bytes, true).0) }
sha256.rs:143:    pub const fn from_byte_array(inner: [u8; 32]) -> Self { Midstate(inner) }
sha256.rs:157:    pub const fn to_byte_array(self) -> [u8; 32] { self.0 }
sha256.rs:165:    pub const fn hash_tag(tag: &[u8]) -> Self {
sha256t.rs:113:    pub const fn to_byte_array(self) -> [u8; 32] { self.0 }
sha256t.rs:116:    pub const fn as_byte_array(&self) -> &[u8; 32] { &self.0 }
sha256t.rs:119:    pub const fn from_byte_array(bytes: [u8; 32]) -> Self { Self::internal_new(bytes) }
siphash24.rs:93:     pub const fn with_keys(k0: u64, k1: u64) -> HashEngine {
siphash24.rs:111:    pub const fn new() -> HashEngine { HashEngine::with_keys(0, 0) }
util.rs:203:            pub const fn to_byte_array(self) -> <$hash as $crate::Hash>::Bytes {
util.rs:208:            pub const fn as_byte_array(&self) -> &<$hash as $crate::Hash>::Bytes {
util.rs:213:            pub const fn from_byte_array(bytes: <$hash as $crate::Hash>::Bytes) -> Self {
```

*  (Eventually) a way to distinguish `KnownPreimage`/`UnknownPreimage` so that we can prevent people from e.g. signing opaque hash blobs without making a solemn oath that they mean to do so. But we should revisit that later because it's a big invasive API change and will likely have its own issues with the Rust language.

Not yet done.

**Comment by Kixunil** [comment]
> * An API where it is easy/obvious how to just hash some data from a file or something.

I think we should have easy to find functions:

```rust
pub fn hash_bytes(bytes_to_hash: &[u8]) -> Self;
pub fn hash_chunks<I>(byte_chunks_to_hash: I) -> Self where I: IntoIterator, I::Item: AsRef<[u8]>;
#[cfg(feature = "std")]
pub fn hash_reader(reader: &mut impl std::io::Read) -> Self;
```

**Comment by apoelstra** [comment]
Yeah, there is more work to be done on sha256t. It's on my list.

Agreed with @Kixunil that we don't need KnownPreimage tagging. Though I think it's fine to keep `from_byte_array`/`to_byte_array` with the existing names even. They're clumsy to type and are very obviously "casting away the type information", which I think is all we need to sufficiently discourage their use.

**Comment by tcharding** [comment]
> > * An API where it is easy/obvious how to just hash some data from a file or something.
> 
> I think we should have easy to find functions:
> 
> ```rust
> pub fn hash_bytes(bytes_to_hash: &[u8]) -> Self;
> pub fn hash_chunks<I>(byte_chunks_to_hash: I) -> Self where I: IntoIterator, I::Item: AsRef<[u8]>;
> #[cfg(feature = "std")]
> pub fn hash_reader(reader: &mut impl std::io::Read) -> Self;
> ```

I don't follow, did you mean one/any of these:
1. Rename the current inherent functions `hash` and `hash_byte_chunks`, and add `hash_reader`
2. Rename the current trait methods `hash` and `hash_byte_chunks`, and add `hash_reader`
3. Add module level functions eg, `sha256::hash_bytes`

**Comment by Kixunil** [comment]
Both `sha256::hash_bytes()` or `Sha256::hash_bytes` sound good. It's true `hash` exists but we need to move it to be inherent. Should we rename it to `hash_bytes`? IDK.

**Comment by tcharding** [comment]
`hash` is an inherent function on `master` already.

**Comment by benma** [comment]
Related: https://github.com/rust-bitcoin/rust-bitcoin/issues/647 - you might want to consider being able to choose the actual underlying hashing implementations.

**Comment by Kixunil** [comment]
@benma good that you mention it. I thought the issue is basically resolved since we added CPU-specific impls but your issue is about binary size.

Sadly, there's no nice mechanism in Rust to just define an impl globally. The only exception is the global allocator. I vaguely remember someone trying to make it available to other crates but can't remember where I've seen it.

I think the only reasonable way to do this is to hash manually and maybe we could have methods that take hash engines later when things are stabilized. Sadly, it'll be annoying for you but the only sane solution I see is to change Rust itself.

**Comment by apoelstra** [comment]
I would be willing to add a `cfg` flag (*not* a cargo feature) which stubbed out all the hash functions into ones that call `extern "C"`  functions that the user is responsible for linking in.

It might also by interesting to use this mechanism for our stubbed-out-hashes

But I think this'll be a lot of work to use in practice.

**Comment by Kixunil** [comment]
Maybe only have it for common functions like SHA256? There's one more problem though: the hash engine state might need to be different for those extern functions and I have no idea how to change it. Perhaps a different solution would be for users to manually `[patch]` hashes.

**Comment by benma** [comment]
@apoelstra could you elaborate? What do you mean by cfg flag?  And why `extern "C"`?

**Comment by Kixunil** [comment]
@benma basically you'd have to compile with `RUSTFLAGS=--cfg bitcoin_hashes_extern_sha256 cargo build --release`. `extern "C"` because there's no other option. (although maybe extern Rust works too if you link Rust code?)

**Comment by benma** [comment]
One could also imagine that all functions that need a hash function take a generic type param instead.

Or we could keep bitcoin-hashes for hashing, but use generic type params in rust-bitcoin, rust-bip39, etc. with bitcoin-hashes as the default implementation, but users could plug in their own. Similar to the `digest::Digest` trait, but more specific to which algo needs to be used (sha256, sha512, ...).

**Comment by apoelstra** [comment]
@benma we definitely can't add a generic parameter to `Transaction::compute_txid`, all the sighashing methods, etc etc., to support such a narrow slice of users.

**Comment by benma** [comment]
Too bad generic modules aren't a thing. I guess the extern "C" thing might be the most practical then. Pretty neat workaround, I didn't consider that before.

**Comment by Kixunil** [comment]
Hopefully `hashes` get more stable over time, so `[patch]` will be feasible. Or at least we could move out SHA256 or whichever algos you need.

> Too bad generic modules aren't a thing.

Exactly! I want them so badly...

**Comment by tcharding** [comment]
Except for the known pre-image thing it looks like this list is done - shall we close this?

Note we have https://github.com/rust-bitcoin/rust-bitcoin/issues/2937 discussing the known pre-image thing.

**Comment by apoelstra** [comment]
Yep, let's close this. I think our API is much stronger now.
