### ISSUE TITLE
Tracking issue: Release `primitives v0.101.0`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3035]
This is the game plan I'm working off, please consider it theoretical unless there is a linked PR

- [x] Literally empty crate: #2950
- [x] Move `opcodes` module into `primitives`: #2989
- [x] Move scriptpubkey stuff out of `Script` into an extension trait: #2955
- [x] Move locktimes and `Sequence` to `primitives`: #2991
- [x] Decide on and implement re-export policy: #3037 
- [x] Move script module into primitives: #3431 
- [x] Move `Transaction` and friends into `primitives`: #3510
- [ ] Move `Block` into `primitives` with optional `Block::compute_blockhash`: #3549

The `primitives` crate is our top priority, please consider prioritising review of PRs related to this work, I'll use the [milestone](https://github.com/rust-bitcoin/rust-bitcoin/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Release+%60primitives+v0.100.0%60%22) to help filter. Also I'll use `P-High` label to indicate the next step required.

**Comment by tcharding** [comment]
Idea for the text above, credit to @apoelstra (normal caveat, all mistakes are my own).

**Comment by tcharding** [comment]
Also, my normal caveat about not being that experienced with project management, holla at me if you want to see something different that is more helpful.

**Comment by Kixunil** [comment]
> * (instead of wrapping eg `hashes::sha256::Hash`)

What does it mean and why do it that way?

**Comment by apoelstra** [comment]
>What does it mean and why do it that way?

Our intention is to make `hashes` optional. I think we can do this and only lose a few things (e.g. `Transaction::compute_txid`) if the hash types themselves are just dumb 32-byte array wrappers.

**Comment by Kixunil** [comment]
> Our intention is to make `hashes` optional.

:open_mouth: isn't it too much? Although it could help @benma and we wouldn't have to create funny `hash_newtype_api_stable_v1` macro. :thinking:

**Comment by apoelstra** [comment]
I had initially thought it was too much, but then we realized how easy it would be :). And true! If @benma was willing to implement his own `compute_txid` method (not hard, our impl is 4 LOC and only calls public methods) then he'd be able to use his own hashes impl without any crazy configure flags or anything.

**Comment by benma** [comment]
Thanks for thinking of me :smile: I don't need `compute_txid` though at all, and dead code elimination means it's not a real concern it's optional or not (it just helps a bit to avoid accidentally pulling it in). 

Even if I used `compute_txid` and had a re-implementation for it, the hashing functions of bitcoin-hashes still end up in my binary because they are used in many other places where re-implementations would not be worth it. https://github.com/rust-bitcoin/rust-bitcoin/issues/647#issuecomment-2226969049 would work a lot better as a general solution for me.

**Comment by tcharding** [comment]
I'm lost as to what is the next step for `primitives`. Are we prioritising `push_decode` and creating a `consensus-encoding` crate or are we moving consensus stuff to primitives first?

**Comment by apoelstra** [comment]
Personally I think we should copy the existing encoding traits into `primitives` as private traits so that we can use them internally to implement `compute_txid` etc.

It's ugly but it'll get us moving forward.

**Comment by tcharding** [comment]
Aight, thanks, I remember now you saying this before. I'm likely to be a bit sketchy this week with the jet lag and all :)

**Comment by Kixunil** [comment]
I don't think I can manage to do it until the end of this week but hopefully I can the next one.

Also maybe rather than copying, just don't move `compute_txid` yet. Let `primitives` be just PODs for now.

**Comment by apoelstra** [comment]
@Kixunil it's not just `compute_txid`, it's also several other methods, and most importantly, `fmt::Display`, which can't be added via extension trait. So I think maybe it's worth the ugliness to sneak the encoding stuff in. And the main cost, code size, is not really too important here because our target use case is demoing API usage, not releasing a production-grade verson of the library.

OTOH, I took a quick glance at `miniscript` and we only use `compute_txid` in the PSBT module, which we could feature-gate or disable in a `primitives` demo.

So maybe we should try to move forward without, and before release, assess how much extra functionality would be needed for rust-miniscript (as a prototypical `primitives` user). And if we're pretty-much there we can go ahead and just release 0.1 -- semver-tricking 0.1.1 to use a later version that adds `fmt::Display` and other missing functionality -- but if we find that we need a dozen extra methods and they all depend on encoding, that's a sign that we should just put the hidden encoding traits in.

**Comment by Kixunil** [comment]
Do we really have to have `Display` on `Transaction` from the start? It's not currently in the released API anyway. We can have a method in extension trait for now or just let people call `consensus_encoding::serialize_hex`.

Also I was unsure what the fuss with `miniscript` is about but now I've remembered you want to break the dependency loop and export `miniscript` from `bitcoin`. Honestly I think this is really not super important and it can stay as-is for one more release.

> semver-tricking

No semver-tricking should be needed and if we're in situation where it would be it probably won't be possible/usable at all.

Disclaimer: I also want `primitives` to be reasonably useful. E.g. if we can use it together with p2p in electrs that could nicely improve compile time. However given we have developer time constraints I think a more realistic approach is to get something usable out and then improve it progressively rather than wait an release a huge chunk of work.

Also, I've now realized that `bitcoincore-rpc` might be a better prototypical `primitives` user.

**Comment by apoelstra** [comment]
> We can have a method in extension trait for now or just let people call `consensus_encoding::serialize_hex`.

Ok, sure, as long as `consensus_encoding` exists and its traits are implemented for everything in `primitives` as soon as we're ready to release. We absolutely cannot have a "lol we removed `hex` but don't worry we'll replace it in 6 months" situation like we did with rust-bitcoin 0.30.

> Also I was unsure what the fuss with `miniscript` is about but now I've remembered you want to break the dependency loop and export `miniscript` from `bitcoin`. Honestly I think this is really not super important and it can stay as-is for one more release.

If we want this to be usable and get testing, then we should take `miniscript` seriously.

> No semver-tricking should be needed and if we're in situation where it would be it probably won't be possible/usable at all.

It's never *needed*. But I think it would be possible, and useful, if it turned out that `primitives 0.2` had a `Transaction` type which was the same as the one in `primitives 0.1` except that it also had `fmt::Display`.

> Also, I've now realized that `bitcoincore-rpc` might be a better prototypical `primitives` user.

I guess you mean `bitcoind-json-types` and `bitcoind-json-client`, since `bitcoincore-rpc` is basically unmaintained. But yes, getting the RPC crates to use a stable version of primitives would be a godsend.

**Comment by Kixunil** [comment]
> Ok, sure, as long as `consensus_encoding` exists and its traits are implemented for everything in `primitives` as soon as we're ready to release.

Yeah, I was always planning to do that.

> We absolutely cannot have a "lol we removed `hex` but don't worry we'll replace it in 6 months" situation like we did with rust-bitcoin 0.30.

We did not remove hex formatting, just made `Display` the primary API. Big difference. The real problem was that (a) people were depending on `bitcoin_hashes::hex` for their arbitrary code or to cover our API holes (I think, I'm not sure) and didn't want to change it and (b) didn't want to change `to_hex` to `to_string` for some reason.

> If we want this to be usable and get testing, then we should take `miniscript` seriously.

I mean it felt to me like `minisript` is some "king crate" that determines which API is good while there are multiple other projects that have both similar and different needs. Thus any reasonable set of crates should work and doesn't require `miniscript` if the entire API is used.

> if it turned out that `primitives 0.2` had a `Transaction` type which was the same as the one in `primitives 0.1` except that it also had `fmt::Display`.

Then we would do `primitives` 0.1.1 rather than 0.2.

> I guess you mean `bitcoind-json-types` and `bitcoind-json-client`, since `bitcoincore-rpc` is basically unmaintained.

Haven't noticed it was forked already. Nice.

**Comment by apoelstra** [comment]
Ok, great, agreed on all counts (other than the history of `hex`, but that's water under the bridge).

**Comment by tcharding** [comment]
There are a lot of moving parts here to remember, if I push PRs that contradict any "current" ideas you hold please take it simply as I forgot not that I'm trying to push a different way. I'll try to keep pushing discreet PRs that are reviewable and mergable and that move us somewhat in the direction we are going.

**Comment by tcharding** [comment]
If you want to use an issue this one is as good as any I'd say. I'm totally open to learning better ways/tools to do project management. I don't think I use github that well for more complex projects like this `primitives` work.

**Comment by Kixunil** [comment]
I just wanted to track every single step required to *stabilize* `primitives`. Including things like tagged script. But I'd change the title to say "stabilize".

**Comment by tcharding** [comment]
I renamed this issue and added https://github.com/rust-bitcoin/rust-bitcoin/issues/3133

**Comment by tcharding** [comment]
Relevant comment about release strategy `primitives v0.100.0` and `v1.0.0`: https://github.com/rust-bitcoin/rust-bitcoin/pull/3110#issuecomment-2258471476

**Comment by EdsonAlcala** [comment]
what is the status of this issue?

**Comment by tcharding** [comment]
I edited the main text then realized doing so makes the thread stale.

**Comment by apoelstra** [comment]
Can you remind me or link to where we decided to release primitives starting from 0.100.0?

**Comment by tcharding** [comment]
100 is actually released already, I updated the title. We did it because we took over the crate from the C++ transpiling project, remember the lad doing that kindly gave it to us.

**Comment by apoelstra** [comment]
Ahh that's right, thanks!

**Comment by tcharding** [comment]
I removed the `AsRawTransaction` thing from the list, that is @Kixunil's along with push decode. We might be ready to release before he is back.

**Comment by tcharding** [comment]
Hey @apoelstra I went through the 2 pages of issues that show up if one filters by 'primitives' and I don't see anything urgent for `v0.101.0` - do you want to take a quick look sometime please?

**Comment by tcharding** [comment]
We are getting close, closing this in favour of the release tracking PR.

I believe the `AsRawTransaction` stuff may not be needed because we manually implemented `compute_txid` but I may be missing something.

**Comment by apoelstra** [comment]
LGTM. And yes, I view `compute_txid` as critical functionality, but pretty-much nothing else is critical.
