### ISSUE TITLE
[epic] Tracking issue for bitcoin_num adoption

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#467]
# Action points

These points have to be completed step by step:
- [x] Create bitcoin_num crate transferring all hex, endian and number-related helper macro functions from both bitcoin_hashes and rust-bitcoin http://github.com/LNP-BP/bitcoin_num/
- [x] Publish bitcoin_num to crates.io https://crates.io/crates/bitcoin_num
- [x] Create a PR adopting bitcoin_num for bitcoin_hashes https://github.com/rust-bitcoin/bitcoin_hashes/pull/91
- [ ] Move bitcoin_num to rust-bitcoin GitHub org
- [ ] (optionally) add @dr-orlovsky to rust-bitcoin GitHub org as a member
- [ ] Review & merge https://github.com/LNP-BP/bitcoin_num/pull/1
- [ ] Review & merge https://github.com/LNP-BP/bitcoin_num/pull/2
- [ ] Review & merge https://github.com/LNP-BP/bitcoin_num/pull/3
- [ ] Review & merge https://github.com/LNP-BP/bitcoin_num/pull/4
- [ ] Review & accept PR adopting bitcoin_num for bitcoin_hashes
- [ ] Create a PR adopting bitcoin_num for rust-bitcoin
- [ ] Review & accept PR adopting bitcoin_num for rust-bitcoin
- [ ] Bump and publish new bitcoin_hashes version
- [ ] Bump and publish new rust-bitcoin version

PS. Here is copy of the original issue opening post:

It seems `util::endian` https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/endian.rs is is just a copy-paste from https://github.com/rust-bitcoin/bitcoin_hashes/blob/master/src/util.rs#L149-L210

Is there any specific reason of doing that or just a mistake? Why not to export functions from `bitcoin_hashes` and import them at rust-bitcoin?

**Comment by sgeisler** [comment]
Exporting them from `bitcoin_hashes` would be super weird, it just doesn't belong there conceptually imo. Ideally we'd have a util crate for these things, but this seems to slow down development due to releases/version bumps.

**Comment by sgeisler** [comment]
`bitcoin_util`would be super useful indeed. I have searched for hex stuff far too often :grimacing: and I guess it might change sufficiently rarely to not make it too annoying.

**Comment by dr-orlovsky** [comment]
Here it is: https://github.com/LNP-BP/bitcoin_num
This covers:
* endianess-related functions from both bitcoin_hashes and rust-bitcoin
* big int (uint mod) functionality and its fuzz tests
* hex mod from bitcoin_hashes
* all related tests
* internal macros from rust-bitcoin

All code is not in master, but in branches, for easier review: https://github.com/LNP-BP/bitcoin_num/pulls
1. Original code as it was present in the original repos (nothing changed): https://github.com/LNP-BP/bitcoin_num/pull/1
2. Some additions to endian functions on top of that: https://github.com/LNP-BP/bitcoin_num/pull/2
3. Cargo fmt (which is a good practice): https://github.com/LNP-BP/bitcoin_num/pull/3

I am up for moving this to rust-bitcoin github org.

If you ACK the concept, I will prepare PRs to rust-bitcoin and bitcoin_hashes removing this code from there and using this new crate.

Regarding the naming: for now this crate is 100% related to different number-related functions. Also, `util` is already used as a mod name inside rust-bitcoin (and there is a lot which was not moved here and clearly belongs to rust-bitcoin itself, like bip's), so naming it with `util` will create additional confusing. But if there will be consensus for renaming, I will follow.

**Comment by sgeisler** [comment]
utACK. I think we should first get an initial version released before opening PRs to rust-bitcoin.

**Comment by dr-orlovsky** [comment]
Initial version released: https://crates.io/crates/bitcoin_num

**Comment by apoelstra** [comment]
concept ACK

**Comment by dr-orlovsky** [comment]
I have created roadmap for the crate adoption: pls check the updated issue description

**Comment by elichai** [comment]
Should we use this opportunity to remove the `U128` type? we now have `u128` support after we bumped to 1.29
(although maybe I'd leave the macro generation so we can create a U128 type for fuzzing/testing against `u128`)

**Comment by dr-orlovsky** [comment]
Good point; I will add a PR to bitcoin_num with that and will update todos

**Comment by apoelstra** [comment]
@dr-orlovsky can you PR to move this crate into a subdirectory, and add another directory with bitcoin-num in it. We can use cargo workspaces to maintain both crates in this repo, which I think will make maintenance and testing easier.

I think we should do the same thing with bitcoin-constants, and maybe move some of the block/transaction parsing stuff to a new bitcoin-primitives crate.

**Comment by stevenroose** [comment]
Can I perhaps bring up the suggestion that moving our hex stuff from `bitcoin_hashes` to `bitcoin_num` doesn't really make it be ina a more sensible place :sweat_smile: And it sounds like bitcoin_num would be just hex + uint256 + perhaps the endian stuff. I'm unsure what's the advantage of moving them into a "num" crate, tbh.

**Comment by dr-orlovsky** [comment]
Endian stuff is get reused between `bitcoin` and `bitcoin_hashes` with some functions being duplicated. The idea of separate crate came from this issue as a response to it: https://github.com/rust-bitcoin/rust-bitcoin/pull/436#issuecomment-686609818

**Comment by TheBlueMatt** [comment]
Creating an entire crate to remove some trivial code duplication for code that should never change seems like killing a fly with a bazooka.

**Comment by stevenroose** [comment]
I agree. We don't seem to need this. Also, Rust stdlib has these methods already in stable, so these are really just a stopgap until we can use stdlib functions.

**Comment by apoelstra** [comment]
I think the aversion to having extra crates is misplaced. We can have multiple crates in the same repository, make sure their versions are incremented in sync, etc. I think Matt's concerns are (a) every extra crate is an extra rustc invocation when you use things outside of cargo, (b) it makes the output of `cargo tree` bigger.

The first is really not an issue. Bitcoin Core is now split into five or six distinct libraries and the only people who care are the ones currently editing the Makefile.

The second is an ergonomic problem with `cargo tree`, but one that's manageable. If you are auditing your dependencies beyond "yup, looks like there aren't very many" then you should have written down somewhere that bitcoin, bitcoin_hashes, secp, etc., are all maintained by the same set of people and represent the same trust set.

I agree that doing it for endianness is pointless, although if we had a `num` crate that also dealt with the u256 types, the weird OpenSSL float encoding in `nBits`, difficulty adjustment etc., maybe that would be more interesting.

However, I think it may be worthwhile to split a couple crates for:
* primitives, so that #526 (which comes up every month or two) would be pointless, and people just just parse primitives without pulling a zillion other things in. e.g. rust-elements needs to parse some bitcoin primitives to parse pegin witnesses and otherwise does not care about Bitcoin at all
* encoding, so that we can provide a uniform interface for bech32/base58/base64/hex, and again, people can use it without pulling in the entire dep tree of rust-bitcoin. e.g. rust-secp could depend on this and then it'd be sanely possible to base58-encode secret keys or base64-encode recoverable signatures

**Comment by Kixunil** [comment]
One more reason for a separate crate is that duplicating types becomes pain if they are used in public interfaces. Didn't check deeply enough if it applies in this case, just guessing based on existence of `U256`.

**Comment by dpc** [comment]
> The second is an ergonomic problem with cargo tree, but one that's manageable. If you are auditing your dependencies beyond "yup, looks like there aren't very many" then you should have written down somewhere that bitcoin, bitcoin_hashes, secp, etc., are all maintained by the same set of people and represent the same trust set.

`cargo-crev` does implement some things around "trust set" (by scrapping owners for each crate from crates.io). Though I'm not sure if it will support exactly what you want. It could be possibly added.

**Comment by apoelstra** [comment]
I think it will accidentally do the right thing for us, since I am the sole owner for rust-bitcoin, rust-secp, bitcoin_hashes. (Although we should really change that because a bus factor of 1 is not good..)

**Comment by apoelstra** [comment]
Fixed the bus factor.

**Comment by dr-orlovsky** [comment]
Closing since we have already agreed on a different crate split strategy in #550.

If there will be a need to revive `bitcoin_num` as a part of that work pls let me known; archiving that repo for now.
