### ISSUE TITLE
[epic] PSBT and related BIP 32 refactoring tracking issue

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#473]
Over the last week I have created a number of PRs focused on brining rust-bitcoin PSBT implementation closer to the specifications (BIP 174, with dependencies on BIP 32 and CLIP 132). Here I summarize all related PRs and their merge status (with flags), including older PRs by this community.

## PSBT general
- [x] #478 (#465 previously) add hash preimage keys to PSBT inputs
- [x] #471 adding other generic key types and support for proprietary keys from BIP 174
- [x] #499 adding support for new global types (Xpub, version)
- [x] #530: replacing all PSBT key types with constants
- ~~[ ] WIP: converting PSBT key types to be enum, not consts~~ (was decided that it is not feasible)
- [x] #497: serde serialization of PSBT data (for inspection etc)
- [x] Display/FromStr serialization for `SigHashType` (part for the PR above^^^)

~~## PSBT roles/responsibities~~
~~- PSBT roles/responsibilities API discussion https://github.com/rust-bitcoin/rust-bitcoin/issues/455~~
~~- [x] #472 PSBT roles~~
~~- [x] #456 alternative approach for PSBT roles (closed)~~
~~- [x] #457 yet another alternative approach for PSBT roles~~

## BIP 32 dependencies:
~~- [ ] #469 implementation of ypub/priv, zpub/zprv and other formats according to BIP 32 and SLIP 132~~ (SLIPs should not be a part of rust-bitcoin)
~~- [ ] #279 alternative older proposal for y/zpubs~~ (ibid)
- [x] #470 binary encoding of extended pub and priv keys according to BIP 32
- [ ] #498 improvements to derivation path function
- [x] #513 Nit: making input and output field names match spec type names
- [x] #480 `KeySource` type for `(Fingerprint, DerivationPath)` tupes

## BIP PRs
These are not parts of rust-bitcoin, however still related:
- [ ] https://github.com/bitcoin/bips/pull/988 require creator to initialize empty output fields
- [x] https://github.com/bitcoin/bips/pull/989 rename responsibilities->roles to match Bitcoin Core
- [x] https://github.com/bitcoin/bips/pull/990 fixing typo in rationale reference
