### ISSUE TITLE
Tracking issue for Taproot

### ISSUE THREAD

**Issue by jrawsthorne** [rust-bitcoin/rust-bitcoin#503]
Wanted to create an issue to track the various changes needed for taproot support

# Tagged hashes

- [x] Merge https://github.com/rust-bitcoin/rust-bitcoin/pull/259 for tagged hashes

# Signatures & PSBTs

- [x] Unified SighashCache implemented in #628 
- [x] Signature data serialziation according to BIP-341 in witness and BIP-371 in PSBTs: #671
- [x] PSBT taproot-specific fields: #681, #671

# Script

- [x] new_p2tr() #563, #691 [requires rust-bitcoin/rust-secp256k1/pull/237]
- [x] to/is_p2tr() #696 (previous work: #646)
- [x] Construction of taproot script branches and script conversion to P2TR #677 (previous attempt: #666)
- [x] Test coverage #695 
- [x] Converting `LeafVersion` into an enum #718

# Opcode

- [x] OP_CHECKSIGADD #644 

# Address

- [x] Witness version type introduction: #617 
- [x] AddressType::P2t #563 [requires rust-bitcoin/rust-bech32#48]
- [x] p2t(pubkey: secp256k1::bip340::PublicKey, network: Network) #563 [requires rust-bitcoin/rust-secp256k1/pull/237]
- [x] address_type match segwit version 1 to AddressType::P2t #563
- ~~Address-related type refactoring for better witness v1 support:~~ #668

# Key

- [x] Key refactoring strategy: https://github.com/rust-bitcoin/rust-bitcoin/issues/588 and its step-by-step implementation:
    * [x] Non-API breaking changes for `0.26.1` #589 
    * [x] Refactor key export names #757
    * [x] API-breaking changes to Extended keys internal key representation: #590 
    * [x] API-breaking changes to PSBT internal BIP32 key representation: #591 
- [x] Support for proper key tweaks: #677 & #696 (previous work: #585, #666; parallel/alternative #604)
- Rejected first implementation attempt, but a lot of important discussions on implementation details https://github.com/rust-bitcoin/rust-bitcoin/pull/561
- Other Important discussions addressing Taproot as a part of overall crate refactoring: https://github.com/rust-bitcoin/rust-bitcoin/issues/550

**Comment by Kixunil** [comment]
Would be cool if someone with edit access to https://en.bitcoin.it/wiki/Bech32_adoption updated status to WIP (the table at the very bottom)

**Comment by dr-orlovsky** [comment]
I assume we are also blocked by the release of rust libbitcoinconsensus wrapper lib supporting Taproot?

**Comment by apoelstra** [comment]
@dr-orlovsky I thnk it's okay to cut a release without libbitcoinconsensus being updated

**Comment by sanket1729** [comment]
I believe the primary blocker now is a rust-secp release. 

I believe one of the maintainers added 
> Changes to BIP32 extended key derivation API: WIP

I don't think there is anything needed to change in bip32 for taproot/schnorr. Github edit history says that it was @dr-orlovsky . Maybe we should discuss this before you make any progress

**Comment by apoelstra** [comment]
Opened a PR for a rust-secp release.

https://github.com/rust-bitcoin/rust-secp256k1/pull/347

What exactly do we need from this? Do we need to do an update of the underlying C lib?

**Comment by sanket1729** [comment]
We need the bug fix that required signing context schnorr signature verification. Some additional APIs for tweaked keypairs that were not released previously. And the new APIs that refer to keys are XOnlyPubKey/EcKey instead of schnorr::PublicKey.

We do not need an update to the underlying C lib.

**Comment by dr-orlovsky** [comment]
@sanket1729 I agree it is not needed, removing. Also removing the part mentioning closed PR: "Address-related type refactoring for better witness v1 support"

**Comment by apoelstra** [comment]
rust-secp release done - 0.21.1. (Yesterday we did 0.21.0 but forgot to export the new `Parity` type)

**Comment by sanket1729** [comment]
Remaining PRs for taproot release:

- #755 (#590, #591, and #696 depend on this) 
- #696
- #590 
- #591 
- #669 
- #718

**Comment by dr-orlovsky** [comment]
#755 is merged, the rest of PRs can be rebased now. I update my PRs this evening

**Comment by dr-orlovsky** [comment]
So, now we have the following PRs updated for the review:
- #696
- #669
- #718

This PRs will probably require new secp point release (the second is based on the first one):
- #590
- #591

**Comment by dr-orlovsky** [comment]
Congrats: for now we have just two PRs left, which are purely code-style PRs:

- #778 
- #757

Even without them merged I think we are good to go for the first RC on `0.28` here

**Comment by Kixunil** [comment]
Wow, I didn't even realize we are this close!

I think the last two have a good chance of being included, they aren't too hard.

**Comment by sanket1729** [comment]
There are two more bugs that we need to resolve. 
- #776 
- #779

**Comment by dr-orlovsky** [comment]
Looks like we are done here! Congratulations to everyone!
