### ISSUE TITLE
Tracking issue for clippy

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#807]
- [x] Add `clippy.toml`
- [ ] Fix all current lints or ignore non-useful ones (many fixed, some still WIP)
- [ ] Are there interesting clippy lints turn off by default that we should turn on?
- [ ] Enforce in CI

**Comment by tcharding** [comment]
Its my impression that its best to wait for edition 2018 before tackling this, there will be less churn and less dramas once Rust 1.29 is dead and buried.

**Comment by Kixunil** [comment]
I don't disagree but wouldn't block PRs that fix things before 2018. There's still a bunch of things that can be done. One of the MSRV-related clippy bugs got even fixed recently.

**Comment by tcharding** [comment]
Are there any other lints folks want turning on, otherwise we can close this.

**Comment by Kixunil** [comment]
@dpc mentioned denying `as_conversions`, which sounds great to me. I will try to scroll through others soon.

**Comment by Kixunil** [comment]
Oh:

```rust
$ cargo +nightly clippy --all-features 2>&1 | grep '^error: ' | wc -l
276
```

**Comment by tcharding** [comment]
Yeah I tried that one too and quickly put it in the 'too much work for now' basket :)

**Comment by dpc** [comment]
Were these legitimate uses? Some uses of `as` casts might be unavoidable, and will have to be whitelisted.

**Comment by Kixunil** [comment]
@dpc I don't know, I didn't read all of them. Some of them probably are. I believe we have at least `something_u32 as usize` that can't be solved by any method provided by `core` and we explicitly don't support 16-bit archs.

IMO the best way to address those is to have dedicated functions (extension traits) for these cases and only whitelist those. E.g. 

```rust
/// Losslessly converts `u32` to `usize`
///
/// Losslesssness is achieved simply by this library not supporting 16-bit architectures
fn to_usize(value: u32) -> usize (
    #[allow(clippy::as_conversions)]
    value as usize
)
```

In the unlikely scenario that one day we decide to support 16-bit archs we could just delete the function and address all the compiler errors.

**Comment by apoelstra** [comment]
Conveniently we could even make the trait's existence dependent on arch sizes >16, so that it "naturally" wouldn't compile on a 16-bit machine.

**Comment by Kixunil** [comment]
Yes, though I'd still like to keep the explicit message which is easier to understand.

**Comment by dpc** [comment]
I was just wondering yesterday how hard would it be to just make a crate like this (with trait extensions), where "minimum required `usize` width" would be a "Cargo feature".

I was also wondering about having `to_usize_checked` which would just be a shorthand for `Self::try_from(value).expect("integer conversion overflow")`

**Comment by dpc** [comment]
Some quick crates.io for similar prior work: https://docs.rs/cast/latest/cast/ - no configurable minimum supporter usize width, and I think I like trait extension suffixed conversion method more.

**Comment by dpc** [comment]
> I was just wondering yesterday how hard would it be to just make a crate like this (with trait extensions), where "minimum required `usize` width" would be a "Cargo feature". This way projects that do not support certain small-width arch, could explicitly state it and get extra conversion methods in return.
> 
> I was also wondering about having `to_usize_checked` which would just be a shorthand for `Self::try_from(value).expect("integer conversion overflow")`

I need it for something I'm cooking, so I did a quick PoC: https://crates.io/crates/convi

The `u64::checked_from` seems quite useful, so far I haven't found a single use for `usize::cast_from` because on minimum requirement of 32 bit arch, it enables only `usize::cast_from` on a `u32`, `i16`, `u16`, `i8, and `u8`, which I haven't spotted in my code yet. :)

**Comment by Kixunil** [comment]
> I was just wondering yesterday how hard would it be to just make a crate

Are you reading my mind? I had this idea years ago but didn't find the time to implement it. :D But recently I realized that I can't implement it to full extent - also supporting `max_pointer_width` and casts in the other direction without causing feature flags to not be additive.

**Comment by dpc** [comment]
>  also supporting max_pointer_width and casts in the other direction without causing feature flags to not be additive.

I was wondering if I should add `max_pointer_width`. My understanding it that they are no breaking additivness. As long as if one crate says `max_target_pointer_width_32` and other ``max_target_pointer_width_64`, and you set the checks to set max to 32 bit everything is OK, AFAICT. The features added perfectly. The sum of max pointer target constrain is the minimal one and that's it. I mean - the current `min_target_pointer_width` works exactly the same just in the other direction.

My problem with `max_target_pointer_width_*` is that there is less excuse for such a constrain. There are often fundamental reasons why the code can't work with 8, 16 bit machine - because it can't even handle the memory sizes necessary for whatever the code is doing. But I can't remember ever the higher width pointer would be a limitation.

**Comment by Kixunil** [comment]
@dpc `min_target_pointer_width_64` + `max_pointer_target_width_32`

One example where it could make sense to cast `usize` to e.g. `u32` is writing some protocol serialization on embedded. I think I've seen something like that somewhere but can't remember the details.

**Comment by sanket1729** [comment]
@tcharding, can this be closed now?

**Comment by Kixunil** [comment]
@sanket1729 I just went over potential new lints and there's a shitload of them :D

**Comment by apoelstra** [comment]
Thanks for looking these up! Unfortunately I have no idea how to discuss 50 separate lints :)

Most of these I'm not familiar with at all. `cognitive_complexity` I've heard bad things about. `shadow_unrelated` I think we should turn on -- we just ran into an issue at Blockstream related to double-locking that this lint would've caught. (I dispute that shadowing was relevant at all here .. it would've caught the bug by noticing two variables both called `lock` but they just as easily could've had different names .. but I also think that reusing variables for unrelated reasons is probably bad form.)

**Comment by Kixunil** [comment]
I would like to try enabling all of them and see what happens. :) Many (most?) of them already shouldn't trigger in our codebase. Some of them are things I complained about in reviews. And if we hit too many FPs with some we can disable.

I heard that `congnitive_complexity` is controversial but it's parametrizeable and I guess there will be places where splitting things up really is helpful. Anyway, I don't mind turning it off if it gets annoying.
