### ISSUE TITLE
Error refactoring

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#820]
## Goals:

1. All errors should be forward-compatible
2. To avoid `unreachable!()` calls functions should only return error variants that can actually happen; catch-all errors may be provided to help people who don't need this.
3. Each error should contain all relevant information about the operation that failed
4. Error information should not be lost in conversions except for explicit methods
5. If the error information is large enough to slow down programs as demonstrated by benchmarks and motivated by real-life use cases we can put it on heap or omit it depending on circumstances. RC/beta versions should help people find out soon enough.

## Motivation/Rationale

1. Forward-compatibility will give us confidence to mark the crate (or its parts after split) 1.0. 1.0 is one of the green flags when picking a crate, a mark of professionalism and dedication to keep the API.
2. Relying on compiler instead of humans scales better with size of the project and number of contributors. This is an often-mentioned reason to use Rust. Eliminating impossible branches also saves a bit of CPU time.
3. From experience, lack of information makes debugging hard. We want to make debugging easy so the development is efficient, enjoyable and possibly saves people from losing satoshis.
4. Same as above.
5. Some crates put error information on heap to make moving around faster. Judging between heap allocation cost and memcpy cost is difficult without knowing the use cases and differs depending on the code. Avoiding heap is simpler (the default in Rust) thus doing anything else is premature optimization

## Tasks

Ordered for efficiency, not strict.

- [ ] Enable `secp256k1/bitcoin_hashes` and use conversions from there - this is low-hanging fruit, obvious cleanup to be done first
- [ ] Consider using `genio` or NIH similar traits to avoid `.expect()` calls.
- [ ] Inspect error handling for other potential cases of impossible errors and try to avoid **returning** them.
- [ ] Inspect returned errors and remove unneeded variants and/or make new types without them.
- [ ] Inspect all error types, decide if we're confident in exposing the internals and encapsulate what's required - see below

### Forward-compatibility decisions:

* If we're sure no variant can ever be removed from an enum-based error, keep it enum if we're unsure make it `struct Foo(InnerFoo)`
* If we're sure no more variants will be added keep it as is, otherwise add `#[non_exhaustive]`
* For each variant perform similar analysis on the contents of its variants and either hide them in struct or expose them. Hint: if the error type comes from non-stable dependency it MUST be encapsulated. There's a possible conversion trick involving `TryFrom` and a wrapper to avoid branching for some dependency versions
* Check if important information is missing and add it in line with the above steps.
* `From<T> for Error` or vice-versa may only be implemented it `T` is from a stable crate and our error representation is guaranteed to contain `T` or be contained in `T` respectively.

## Unresolved questions

* Should all errors be suffixed with `Error`? I guess no.
* When should errors go to separate module? My suggestion: only if error-related code is large. "Large" is currently not defined.
* Naming of internal errors: `Inner`/`Internal/other prefix/suffix (not affecting stability)

**Comment by tcharding** [comment]
Ha! I knew you'd have some ideas :) Thanks for writing this up.

**Comment by Kixunil** [comment]
Noticed the tracking issue column in the #787 table and there wasn't anything so I created it. :)

**Comment by apoelstra** [comment]
high-level concept ACK. The devil is in the details :)

**Comment by Kixunil** [comment]
@apoelstra seems best to resolve the details in individual PRs.

**Comment by sanket1729** [comment]
Concept ACK. If we go down this route we would end up having a separate error type for each API? Here is a common scenario because of the Error enums are polluted

```rust
enum MyError {
	ErrA,
	ErrB,
	ErrC,
}

pub fn api_1() -> Result<.., MyError> { 
	// Only retuns ErrA and ErrB
}

pub fn api_1() -> Result<.., MyError> { // but only has two variants rechable. 
	// Only returns ErrB and ErrC
}
```
Now, we would end up an error type per API. Maybe that is the way to go, but something feels not nice about this.

**Comment by tcharding** [comment]
Related comment from another PR: https://github.com/rust-bitcoin/rust-bitcoin/pull/881#pullrequestreview-914203982

**Comment by dr-orlovsky** [comment]
Concept ACK.

On some of the details: use of `#[non_exhaustive]` for error types results in one side effect: upstream crates will end up having more `unimplemented!()` parts, since for each error handling case they will have to provide `_ => ` branch in matching, which will not be able to do anything other than have `unimplemented!` in it.

**Comment by dpc** [comment]
> On some of the details: use of `#[non_exhaustive]` for error types results in one side effect: upstream crates will end up having more `unimplemented!()` parts, since for each error handling case they will have to provide `_ => ` branch in matching, which will not be able to do anything other than have `unimplemented!` in it.

I don't think that's the way to handle it. I'd just handle that case in a reasonable way - bubble up and `UnkownError`, etc. Oftentimes libraries don't really care about which error was it anyway.

**Comment by dpc** [comment]
> The difference between unimplemented! and [todo!](https://doc.rust-lang.org/std/macro.todo.html) is that while todo! conveys an intent of implementing the functionality later and the message is “not yet implemented”, unimplemented! makes no such claims. Its message is “not implemented”. Also some IDEs will mark todo!s.

https://doc.rust-lang.org/std/macro.unimplemented.html

I see.

**Comment by tcharding** [comment]
Relevant comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/881#pullrequestreview-919188428

**Comment by tcharding** [comment]
Are there things to be considered along with the MSRV bump e.g., implementing the trait method `source()`?

**Comment by Kixunil** [comment]
`source()` is a very good catch! It makes most sense to me to change the existing `cause()` impls to `source()` as part of MSRV bump and adding `source` where needed (changing `Display`) as part of this effort, so I edited that checklist item as such. The only other thing I can think of is `non_exhaustive` which is already listed.

**Comment by tcharding** [comment]
When we get to checking all the `Display` impls, here is a relevant comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/987#issuecomment-1118661150

**Comment by tcharding** [comment]
Should we consider putting error code down the bottom of files? This idea comes from the idea of putting the most important thing first. Opening a file and seeing all of the `Error` boiler plate immediately is not super useful. Or is this way to subjective?

**Comment by tcharding** [comment]
From my understanding, for v0.29 we are going to just release with just edition 2018 changes and things that we wanted in before that. Is this your understading @Kixunil? This error work is marked in various places as part of v0.29. You are down as the champion @Kixunil so just wanted to check I'm understanding correctly? Cheers

**Comment by tcharding** [comment]
Are we planning on doing this as part of the v0.29.0 release?

**Comment by Kixunil** [comment]
Since we wanted a quicker release I'm OK with moving it to 0.30. We forgot to update the milestones when we decided to do quick release.

**Comment by tcharding** [comment]
On the path to 1.0 we should audit all `Display` implementations for error types because according to https://github.com/rust-lang/project-error-handling/issues/44#issue-897258383 changing them is a breaking change.

**Comment by Kixunil** [comment]
I agree with the counterargument but we still should do audit to minimize annoyance. :)

**Comment by Kixunil** [comment]
Oh, I only now noticed your question about error code. The convention is to put it into `error` module once it starts getting large. This also cleans up the crate doc. Note that there can be multiple `error` submodules, not just one global.

**Comment by tcharding** [comment]
Removing milestone 0.30.0 in favour of 0.31.0 because we have too much on to get this done right now.

**Comment by Kixunil** [comment]
Agree, this isn't even a super-huge problem.

**Comment by tcharding** [comment]
> Each error should contain all relevant information about the operation that failed

We should work out what to do about `String`s in error types because they are a PITA for no-std builds.

**Comment by tcharding** [comment]
re "open questions"

> * Should all errors be suffixed with `Error`? I guess no.
 
I think we have answered this with "yes" now, right?

> * Naming of internal errors: Inner/`Internal/other prefix/suffix (not affecting stability)

Is this still an open question I rekon we just suffixing _all_ errors with `Error`.

(I've abused my PR description editing permissions to discuss another of the open questions inline.)

**Comment by Kixunil** [comment]
> We should work out what to do about `String`s in error types because they are interact badly with no-std/alloc

That's exactly what #1297 is doing.

> I think we have answered this with "yes" now, right?

We tend to do this but I don't see it as a hard rule.

**Comment by tcharding** [comment]
> We tend to do this but I don't see it as a hard rule.

No worries, I'm pretty sure I added suffixes in `taproot` recently based on this rule.

**Comment by apoelstra** [comment]
I think it's worthwhile to make it a hard rule (though we may find ourselves debating what's really an "error"). Then we can easily grep our API for errors that have inconsistent #derives and flag them.

**Comment by Kixunil** [comment]
OK, let's do it, we can revisit it later if needed.

**Comment by tcharding** [comment]
Note on `non_exhaustive`, should it go on empty structs? Is it ergonomical to use such structs (can users match on them still)?

**Comment by Kixunil** [comment]
I believe it should. It makes it impossible for downstream crates to create such error values but that shouldn't be needed and being able to add information later is very useful. We can always remove it if someone needs it and convinces us that we won't add anything anymore but we can't do the opposite.

**Comment by tcharding** [comment]
> Note on `non_exhaustive`, should it go on empty structs? Is it ergonomical to use such structs (can users match on them still)?

FWIW I thought there was a problem with using `== Error` on structs with `non_exhaustive` but I hacked up a demo for myself and I'm convince now that its ok :)

**Comment by tcharding** [comment]
Before releasing v1.0.0 we need to check that we do not include types in the public API that come from dependencies with version < 1.0.0. This can inadvertently happen by implementing `From`, for example `impl From<foo::FooError> for Error` puts `foo::FooError` in our public API.
