### ISSUE TITLE
PR checklist

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#843]
We seem to repeatedly do various mistakes when accepting PRs. In my experience a great way to avoid mistakes is to have a checklist.
GH even allows us to add it as PR template (may be a bit scary for newbies though). As an example LND has this.

Things that come to my mind, feel free to suggest your own or ask for rationale on things (I don't want to write the rationale **now**).

Checklist focus: good APIs, lack of panics, lack of obvious/common bugs (also lack of UB but that is guaranteed by the compiler :))
Non-goals:  extreme performance, formal proofs of correctness

Things marked `BJ` mean "best judgement" - we don't define exact line here and will be decided as needed. The point is to **not forget** about considering this.
Things marked `CMD` mean "contributor may disagree" - if the contributor disagrees he/she MUST provide logical argument why and this is discussed. All developers involved should try to reach consensus. Worst case we vote. (Is voting really a good idea?)

Unless explicitly stated otherwise, requirements on public items are also recommendations for private items.

- [ ] If new type is added
  - [ ] This type is either private or required to be public for the change to be practical `BJ`
  - [ ] If public
    - [ ] The name of the type adheres to Rust API guidelines (`CMD`)
    - [ ] The name of the type doesn't stutter (`CMD` but "I prefer stuttering" is not considered a logical argument)
    - [ ] The type does **not** implement traits the we could regret (mainly `Copy`, `Eq`, `Ord`, `PartialOrd`; rarely `Sync`, `Send`) `BJ`
    - [ ] The type *does* implement obvious practical traits (`Debug`, probably also `Clone`, `PartialEq`, `serde::{Serialize, Deserialize}`) `BJ`
    - [ ] The type is nameable (reexported) unless it intentionally can't be
    - [ ] If the type is obvious newtype giving read-only access to inner type it must implement `AsRef<Inner>` and `Borrow<Inner>`
      - [ ] If enum
        - [ ] Is it really, really certain that no varians will be removed? If not, hide the enum in a newtype struct.
  - [ ] If private
    - [ ] The type does **not** implement any traits that aren't actually used in the code. `Debug` is allowed though.
  - [ ] It is clearly stated whether the type enforces invariants
  - [ ] If the type enforces invariant(s)
    - [ ] Publicly observable invariants are documented
    - [ ] There is exactly one Rust-native constructor (E.g. `StructName { fields }`) in a method returning `Result` enforcing the invariant(s)
    - [ ] Rust-native constructors in infallible methods are only allowed if input types enforce the invariant(s) (presumably stricter)
    - [ ] Fields that aren't allowed to have all values for the invariant(s) to be upheld are strictly private.
    - [ ] The type is in its own private module with minimum code enforcing invariants
  - [ ] `From<Inner> for T` is **not** implemented
  - [ ] Enum or struct with all public fields has `#[non_exhaustive]` unless there's strong reason to believe it will never be changed `BJ`
  - [ ] If the type is error type
    - [ ] Our requirements for error types are obeyed (will add them when hashed out)
  - [ ] `serde` impls branch on human-readable vs non-human-readable formats unless the serialization is obviously the same (e.g. numeric types)
  - [ ] `serde` impls use minimal serialization size unless there is widely-accepted representation (e.g. don't use base64 for things that are commonly hex even though hex is larger)
  - [ ] `Default`/`new` is only implemented for collections
  - [ ] Associated const (or a method) for `ZERO` is provided for non-collections. Possibly other states (`ONE`...)
  - [ ] If `Drop` is implemented
    - [ ] The implementation accesses all fields. If a field doesn't need to be accessed the dropped fields must be moved to a separate type
- [ ] If new function is added
  - [ ] Does it really have to be a method? Does it really have to be a free function? `BJ`
  - [ ] The name adheres to the Rust API guidelines (`CMD`)
  - [ ] If the function could be easily abused it should have a scary name like `dangerous_foo` or `foo_unchecked`
  - [ ] All instances of `panic!()`, `unwrap()`, ... have explanation why they can't happen
  - [ ] All arithmetic operations either use `checked_`, `wrapping_`, `saturating_` or have explanation why overflow is impossible
  - [ ] The function may only return error on bad inputs if it's a constructor enforcing invariants
  - [ ]  If adding another type would be annoying for callers the function must panic on bad inputs and this panic MUST be documented in `## Panics` doc section
  - [ ] If the function is public
    - [ ] If the function returns `Result` the error conditions are documented in `## Errors` doc section
    - [ ] `impl Trait` MUST NOT be used in arguments, use proper generic instead
    - [ ] Is it **certain** that the function will always return this type? If not either use `impl Trait` or a new custom type `BJ`
  - [ ] The types of arguments have minimum requirements (`IntoIterator` is better than collection, `&str` is better than `&String`...)
  - [ ] Closure is the last argument, closure type is also the last type argument (closure *return type* is among the first)
  - [ ] The code has no obvious performance defects (unneeded `clone()`, `collect::<Vec<_>>()`, `to_owned()`...), they are acceptable in tests but discouraged
  - [ ] Tests are added, trivial obvious functions (returning or delegating to inner fields) don't need tests.
  - [ ] If the function processes untrusted inputs it must have fuzz test
- [ ] Conditional compilation is used
  - [ ] Is it truly additive?
  - [ ] Really? Are you sure? Try to "attack it" by finding a weird scenario
  - [ ] If the condition is observable in public API it must have doc attribute
- [ ] New cargo feature is added
  - [ ] The feature is documented in `lib.rs`
  - [ ] The feature is enabled in docs.rs
  - [ ] The feature is additive

**Comment by apoelstra** [comment]
Whew! At first glance this all looks good but it's a really overwhelming list to write all in one place like this.

We could probably use labels `new-cargo-feature-added` `new-function-added` etc and then have a Discussions page which indicates which checklists should apply for which labels.

**Comment by Kixunil** [comment]
Yeah, 55 items and I don't think there are *all* relevant things. Agree that some kind of separation would be useful. Will have to think about it more.

**Comment by sanket1729** [comment]
Wow, thanks for enumerating these. I will have refer to these while reviewing  and hopefully overtime these things would become second-nature

**Comment by thomaseizinger** [comment]
Some of these things like "adhering to Rust API guidelines" and "instances of `panic!`" could be caught by clippy lints.

- https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention
- https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used

**Comment by tcharding** [comment]
There seems to be some bug in clippy, `wrong_self_convention` does not trigger, to verify I put the example from the lint description in the `Amount` impl block
```rust
impl Amount {
    /// Should trigger clippy lint: wrong_self_convention
    fn as_str(self) -> &'static str {
        "should trigger clippy"
    }
```
And `cargo clippy` lints cleanly. I'm no sure if this should be reported, I already reported the same thing for `print_stdout` a while ago https://github.com/rust-lang/rust-clippy/issues/6610

**Comment by sanket1729** [comment]
Perhaps, we should convert this into a doc and commit it in this repo? 

I think this sort of thing is really helpful "How to review rust code starter-kit". I think we can add it in its current form too. If there are more suggestions, we can iterate. Really a low priority amongst other things in the project.
